services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dockabase-prod
    restart: unless-stopped
    networks:
      - dockabase-network

  nginx:
    image: nginx:alpine
    container_name: dockabase-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
    depends_on:
      - astro
    networks:
      - dockabase-network

  certbot:
    image: certbot/certbot
    container_name: dockabase-certbot
    volumes:
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
    command: renew
    depends_on:
      - nginx

networks:
  dockabase-network:
    driver: bridge
