services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dockabase-dev
    ports:
      - "3000:4321"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
