services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dockabase-prod
    restart: unless-stopped
    networks:
      - dockabase-network

  caddy:
    image: caddy:2
    container_name: dockabase-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./dist:/srv/www
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - astro
    networks:
      - dockabase-network

volumes:
  caddy_data:
    name: dockabase_caddy_data
  caddy_config:
    name: dockabase_caddy_config

networks:
  dockabase-network:
    driver: bridge
